spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_mart_app
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #email configuration
  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/

application:
  security:
    jwt:
      secret-key: dfasdfasdgasdgasdgasdgnasdiogjfaiosdhfgashidfas
      expiration: 86400000

  mailing:
    frontend:
      activation-url: http://localhost:4200/activation-account


















