/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookTransactionHistory } from '../models/book-transaction-history';
import { Feedback } from '../models/feedback';
import { User } from '../models/user';
export interface Book {
  archived?: boolean;
  author?: string;
  bookCover?: string;
  createBy?: number;
  createdAt?: string;
  feedbacks?: Array<Feedback>;
  histories?: Array<BookTransactionHistory>;
  id?: number;
  isbn?: string;
  lastModifiedAt?: string;
  modifyBy?: number;
  owner?: User;
  rate?: number;
  shareable?: boolean;
  synopsis?: string;
  title?: string;
}
