/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Book } from '../models/book';
import { User } from '../models/user';
export interface BookTransactionHistory {
  book?: Book;
  createdAt?: string;
  id?: number;
  lastModifiedAt?: string;
  returnApproved?: boolean;
  returned?: boolean;
  user?: User;
}
