/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Book } from '../models/book';
export interface Feedback {
  book?: Book;
  comment?: string;
  createBy?: number;
  createdAt?: string;
  id?: number;
  lastModifiedAt?: string;
  modifyBy?: number;
  note?: number;
}
