/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Book } from '../models/book';
import { BookTransactionHistory } from '../models/book-transaction-history';
import { GrantedAuthority } from '../models/granted-authority';
import { Role } from '../models/role';
export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  birthdate?: string;
  books?: Array<Book>;
  createdAt?: string;
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  firstname?: string;
  histories?: Array<BookTransactionHistory>;
  id?: number;
  lastModifiedAt?: string;
  lastname?: string;
  name?: string;
  password?: string;
  profilePicture?: string;
  roles?: Array<Role>;
  username?: string;
}
